### PR TITLE
Fix stale-base.sha checkout in LLxprt PR Review (Fixes #474)

### PR DESCRIPTION
**Pull request by acoliver**
## Summary

Fixes the deterministic CI failure in the LLxprt PR Review workflow where a PR whose recorded pull_request.base.sha predates the commit that introduced the workflow and its supporting scripts (8d0c45b / PR #466) fails with "Cannot find module .../scripts/ci-quota-check.mjs".

## Root cause

The workflow checked out github.event.pull_request.base.sha and then ran node scripts/ci-quota-check.mjs (and later scripts/pr-review-walkthrough.mjs) against that working tree. Those scripts were introduced by 8d0c45b. For any PR whose base.sha is a strict ancestor of 8d0c45b, the checked-out tree lacks the scripts, producing a hard module-resolution failure that persists identically across reruns until base.sha advances.

Confirmed via git cat-file: scripts/ci-quota-check.mjs and all four pr-review-*.mjs helpers are absent at fccb22b (PR #444's recorded base.sha) and present at HEAD.

## Fix

Change the checkout ref from the possibly-stale base.sha to the base-branch tip (github.event.pull_request.base.ref). The base branch tip is guaranteed to contain every workflow-supporting script regardless of how stale the recorded base.sha is.

Diff scoping is unchanged: base.sha is still fetched (fetch-depth: 0) and still consumed by git merge-base in the "Fetch pull request head" step. Every git diff operation in the workflow uses explicit SHAs ($MERGE_BASE..$PR_HEAD_SHA), never the working tree, so the checked-out ref's only role was to supply the scripts.

## Acceptance matrix

| # | Criterion | Evidence |
|---|-----------|----------|
| A1 | Checkout no longer uses stale base.sha as its ref | tests/core/pr_review_workflow_contracts.rs::checkout_does_not_use_stale_base_sha_as_ref |
| A2 | Checkout resolves base-branch tip (always contains scripts) | tests/core/pr_review_workflow_contracts.rs::checkout_resolves_base_branch_tip + workflow_supporting_scripts_exist_in_repository |
| A3 | base.sha still feeds git merge-base (diff scoping unchanged) | tests/core/pr_review_workflow_contracts.rs::base_sha_still_feeds_merge_base_for_diff_scoping |
| A4 | Regression guard proves the fix structurally | New contract test (RED on main, GREEN on this branch) |

## Verification

- cargo fmt --all --check: pass
- cargo clippy --workspace --all-targets --all-features -- -D warnings: pass
- cargo build --workspace --all-features --locked: pass
- cargo test --test integration pr_review_workflow_contracts: 4/4 pass (was RED before fix)
- Full unit test suite (2574 + 804 tests): pass
- All standalone integration test binaries: pass

The harness_v1_fixtures failures and the guarded_dashboard_reorder_tui_scenario flake are pre-existing environmental TTY/tmux issues (proven to fail identically on clean origin/main via git stash); they are unrelated to this CI-workflow-only change.

## Non-goals

- Changes to product code, dependencies, or ci-quota-check.mjs script logic
- Changes to required product CI (ci.yml)
- Hardening of release.yml (tracked in #471)
- OCR reproducibility-manifest completeness (#464) or OCR config/secrets failures (#158)
- Changing pull_request_target semantics or fork-safety model (both preserved)

## Scope

4 files changed, 268 net insertions (well under the 25-file / 1,500-line target).

### CODE REVIEW

File: tests/core/pr_review_workflow_contracts.rs [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+        .iter()
+        .position(|l| {
+            let trimmed = l.trim();
+            needles.iter().any(|needle| trimmed == *needle)
+        })
+        .unwrap_or_else(|| panic!("step '{step_name}' not found in workflow"));
+
+    let step_indent = lines
+        .get(start + 1)
+        .map_or(8, |l| l.len() - l.trim_start().len());
```
[the remark this answers is not in the document]
Comment (acoliver) [reply tests/core/pr_review_workflow_contracts.rs]: Addressed in commit 7f730330. The step_indent derivation now skips blank lines before computing the indentation, so a future blank line between a step header and its first property can no longer cause the parser to swallow subsequent steps. The suggested approach (find the first line with indent > 0) was applied verbatim. Resolving as fixed.
